# Generated by Django 5.2.12 on 2026-04-02 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ON_SALE', 'On sale'), ('SOLD_OUT', 'Sold out'), ('HIDDEN', 'Hidden')], default='ON_SALE', max_length=10)),
                ('thumbnail_url', models.CharField(blank=True, max_length=500, null=True)),
                ('lowest_price', models.IntegerField(blank=True, null=True)),
                ('seller_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('sales_count', models.IntegerField(default=0)),
                ('popularity_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='idx_categories_parent'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='idx_products_category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='idx_products_status'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['lowest_price'], name='idx_products_lowest_price'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='idx_products_created'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-view_count'], name='idx_products_view_count'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['popularity_score'], name='idx_products_popularity'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='idx_products_name'),
        ),
    ]
