# Generated by Django 5.2.12 on 2026-04-02 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('SELECT', 'Select')], max_length=10)),
                ('options', models.JSONField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('is_comparable', models.BooleanField(default=True)),
                ('data_type', models.CharField(choices=[('NUMBER', 'Number'), ('STRING', 'String'), ('BOOLEAN', 'Boolean')], default='STRING', max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='spec_definitions', to='catalog.category')),
            ],
            options={
                'db_table': 'spec_definitions',
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specs', to='catalog.product')),
                ('spec_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specs', to='catalog.specdefinition')),
            ],
            options={
                'db_table': 'product_specs',
            },
        ),
        migrations.AddIndex(
            model_name='specdefinition',
            index=models.Index(fields=['category'], name='idx_spec_definitions_category'),
        ),
        migrations.AddIndex(
            model_name='productspec',
            index=models.Index(fields=['spec_definition', 'value'], name='idx_product_specs_value'),
        ),
        migrations.AddConstraint(
            model_name='productspec',
            constraint=models.UniqueConstraint(fields=('product', 'spec_definition'), name='uq_product_specs'),
        ),
    ]
