# Generated by Django 5.2.12 on 2026-04-02 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_specdefinition_productspec_and_more"),
        ("commerce", "0001_initial"),
        ("pricing", "0002_pricealert_pricehistory_priceprediction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="CartItem",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "selected_options",
                            models.CharField(blank=True, default="", max_length=200),
                        ),
                        ("quantity", models.IntegerField(default=1)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "product",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="cart_items",
                                to="catalog.product",
                            ),
                        ),
                        (
                            "seller",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="cart_items",
                                to="pricing.seller",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                db_index=False,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="cart_items",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "cart_items",
                        "indexes": [
                            models.Index(fields=["user"], name="idx_cart_items_user"),
                        ],
                        "constraints": [
                            models.UniqueConstraint(
                                fields=("user", "product", "seller", "selected_options"),
                                name="uq_cart_items",
                            ),
                        ],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]

