# Generated by Django 5.2.12 on 2026-04-02 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commerce", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Payment",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "method",
                            models.CharField(
                                choices=[
                                    ("CARD", "Card"),
                                    ("BANK_TRANSFER", "Bank transfer"),
                                    ("VIRTUAL_ACCOUNT", "Virtual account"),
                                ],
                                max_length=20,
                            ),
                        ),
                        ("amount", models.IntegerField()),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("PENDING", "Pending"),
                                    ("COMPLETED", "Completed"),
                                    ("FAILED", "Failed"),
                                    ("REFUNDED", "Refunded"),
                                ],
                                default="PENDING",
                                max_length=10,
                            ),
                        ),
                        ("paid_at", models.DateTimeField(blank=True, null=True)),
                        ("refunded_at", models.DateTimeField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "order",
                            models.ForeignKey(
                                db_index=False,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="payments",
                                to="order.order",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "payments",
                        "indexes": [
                            models.Index(fields=["order"], name="idx_payments_order"),
                        ],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]

