# Generated by Django 5.2.12 on 2026-04-02 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commerce", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Address",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("label", models.CharField(max_length=50)),
                        ("recipient_name", models.CharField(max_length=50)),
                        ("phone", models.CharField(max_length=20)),
                        ("zip_code", models.CharField(max_length=10)),
                        ("address", models.CharField(max_length=200)),
                        (
                            "address_detail",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        ("is_default", models.BooleanField(default=False)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "user",
                            models.ForeignKey(
                                db_index=False,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="addresses",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "addresses",
                        "indexes": [
                            models.Index(fields=["user"], name="idx_addresses_user"),
                        ],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]

