ktor {
  deployment {
    port = 8080
  }
  application {
    modules = [ com.pbshop.ktorshop_exposeddao.ApplicationKt.module ]
  }
}

pbshop {
  apiPrefix = "/api/v1"
  appName = "kotlin-ktor-gradle-exposeddao-postgresql"
}
