# Generated by Django 5.2.12 on 2026-04-02 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_specdefinition_productspec_and_more"),
        ("commerce", "0001_initial"),
        ("pricing", "0002_pricealert_pricehistory_priceprediction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Order",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("order_number", models.CharField(max_length=30)),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("ORDER_PLACED", "Order placed"),
                                    ("PAYMENT_PENDING", "Payment pending"),
                                    ("PAYMENT_CONFIRMED", "Payment confirmed"),
                                    ("PREPARING", "Preparing"),
                                    ("SHIPPING", "Shipping"),
                                    ("DELIVERED", "Delivered"),
                                    ("CONFIRMED", "Confirmed"),
                                    ("CANCELLED", "Cancelled"),
                                    ("RETURN_REQUESTED", "Return requested"),
                                    ("RETURNED", "Returned"),
                                ],
                                default="ORDER_PLACED",
                                max_length=20,
                            ),
                        ),
                        ("total_amount", models.IntegerField()),
                        ("point_used", models.IntegerField(default=0)),
                        ("final_amount", models.IntegerField()),
                        ("recipient_name", models.CharField(max_length=50)),
                        ("recipient_phone", models.CharField(max_length=20)),
                        ("zip_code", models.CharField(max_length=10)),
                        ("address", models.CharField(max_length=200)),
                        (
                            "address_detail",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        ("memo", models.CharField(blank=True, max_length=200, null=True)),
                        ("version", models.IntegerField(default=1)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "user",
                            models.ForeignKey(
                                db_index=False,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="orders",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "orders",
                        "indexes": [
                            models.Index(fields=["user"], name="idx_orders_user"),
                            models.Index(fields=["status"], name="idx_orders_status"),
                            models.Index(fields=["-created_at"], name="idx_orders_created"),
                        ],
                        "constraints": [
                            models.UniqueConstraint(
                                fields=("order_number",),
                                name="uq_orders_number",
                            ),
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="OrderItem",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("product_name", models.CharField(max_length=200)),
                        ("seller_name", models.CharField(max_length=100)),
                        (
                            "selected_options",
                            models.CharField(blank=True, max_length=200, null=True),
                        ),
                        ("quantity", models.IntegerField()),
                        ("unit_price", models.IntegerField()),
                        ("total_price", models.IntegerField()),
                        ("is_reviewed", models.BooleanField(default=False)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "order",
                            models.ForeignKey(
                                db_index=False,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="order_items",
                                to="order.order",
                            ),
                        ),
                        (
                            "product",
                            models.ForeignKey(
                                db_index=False,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="order_items",
                                to="catalog.product",
                            ),
                        ),
                        (
                            "seller",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="order_items",
                                to="pricing.seller",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "order_items",
                        "indexes": [
                            models.Index(fields=["order"], name="idx_order_items_order"),
                            models.Index(fields=["product"], name="idx_order_items_prod"),
                        ],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]

