CREATE TABLE fraud_flags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    price_entry_id BIGINT,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    reason VARCHAR(255) NOT NULL,
    detected_price DECIMAL(15, 2) NOT NULL,
    baseline_price DECIMAL(15, 2) NOT NULL DEFAULT 0,
    approved_by BIGINT,
    rejected_by BIGINT,
    approved_at TIMESTAMP WITH TIME ZONE,
    rejected_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fraud_flags_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_fraud_flags_price_entry FOREIGN KEY (price_entry_id) REFERENCES price_entries(id) ON DELETE SET NULL,
    CONSTRAINT fk_fraud_flags_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_fraud_flags_rejected_by FOREIGN KEY (rejected_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE trust_score_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT NOT NULL,
    score INT NOT NULL,
    grade VARCHAR(10) NOT NULL,
    trend VARCHAR(40) NOT NULL DEFAULT 'STABLE',
    breakdown_json CLOB,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trust_score_histories_seller FOREIGN KEY (seller_id) REFERENCES sellers(id) ON DELETE CASCADE
);

CREATE TABLE translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locale VARCHAR(10) NOT NULL,
    namespace VARCHAR(100) NOT NULL,
    translation_key VARCHAR(191) NOT NULL,
    translation_value CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_translations_locale_namespace_key UNIQUE (locale, namespace, translation_key)
);

CREATE TABLE exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_currency VARCHAR(10) NOT NULL,
    target_currency VARCHAR(10) NOT NULL,
    rate DECIMAL(18, 8) NOT NULL,
    updated_at_exchange TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_exchange_rates_pair UNIQUE (base_currency, target_currency)
);

CREATE TABLE image_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category VARCHAR(40) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    original_path VARCHAR(500) NOT NULL,
    original_url VARCHAR(500) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    size BIGINT NOT NULL,
    processing_status VARCHAR(40) NOT NULL DEFAULT 'COMPLETED',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_image_assets_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE image_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_asset_id BIGINT NOT NULL,
    type VARCHAR(40) NOT NULL,
    path VARCHAR(500) NOT NULL,
    url VARCHAR(500) NOT NULL,
    width INT,
    height INT,
    format VARCHAR(20) NOT NULL,
    size BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_image_variants_asset FOREIGN KEY (image_asset_id) REFERENCES image_assets(id) ON DELETE CASCADE
);

CREATE TABLE badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    icon_url VARCHAR(500),
    type VARCHAR(20) NOT NULL DEFAULT 'AUTO',
    condition_json CLOB,
    rarity VARCHAR(20) NOT NULL DEFAULT 'COMMON',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    badge_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    granted_by BIGINT,
    granted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_badges_badge_user UNIQUE (badge_id, user_id),
    CONSTRAINT fk_user_badges_badge FOREIGN KEY (badge_id) REFERENCES badges(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_badges_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_badges_granted_by FOREIGN KEY (granted_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_fraud_flags_status ON fraud_flags(status);
CREATE INDEX idx_fraud_flags_product_id ON fraud_flags(product_id);
CREATE INDEX idx_trust_score_histories_seller_id ON trust_score_histories(seller_id);
CREATE INDEX idx_image_assets_user_id ON image_assets(user_id);
CREATE INDEX idx_image_variants_asset_id ON image_variants(image_asset_id);
CREATE INDEX idx_user_badges_user_id ON user_badges(user_id);
