// API 경로 상수는 컨트롤러/클라이언트 간 경로 불일치를 줄이기 위해 중앙 관리한다.
export const API_ROUTES = {
  AUTH: {
    BASE: 'auth',
    SIGNUP: 'signup',
    LOGIN: 'login',
    LOGOUT: 'logout',
    REFRESH: 'refresh',
    VERIFY_EMAIL: 'verify-email',
    RESEND_VERIFICATION: 'resend-verification',
    PASSWORD_RESET: 'password-reset',
    SOCIAL: ':provider',
    SOCIAL_CALLBACK: ':provider/callback',
  },
  USERS: {
    BASE: 'users',
    ME: 'me',
    PROFILE: 'profile',
  },
  PRODUCTS: {
    BASE: 'products',
    COMPARE: 'compare',
  },
  CATEGORIES: {
    BASE: 'categories',
    TREE: 'tree',
  },
  ORDERS: {
    BASE: 'orders',
    CANCEL: ':id/cancel',
    RETURN_REQUEST: ':id/return-request',
  },
  PAYMENTS: {
    BASE: 'payments',
    REFUND: ':id/refund',
  },
  REVIEWS: {
    BASE: 'reviews',
  },
  POINTS: {
    BASE: 'points',
    BALANCE: 'balance',
    TRANSACTIONS: 'transactions',
    ADMIN_GRANT: 'admin/points/grant',
  },
  ADDRESSES: {
    BASE: 'addresses',
    DETAIL: ':id',
  },
  WISHLIST: {
    BASE: 'wishlist',
    PRODUCT: ':productId',
  },
  CART: {
    BASE: 'cart',
  },
  SEARCH: {
    BASE: 'search',
    AUTOCOMPLETE: 'autocomplete',
    POPULAR: 'popular',
  },
  PRICES: {
    BASE: 'prices',
    HISTORY: 'history',
    ALERTS: 'alerts',
  },
  COMMUNITY: {
    BASE: 'community',
    BOARDS: 'boards',
    POSTS: 'posts',
    COMMENTS: 'comments',
  },
  INQUIRIES: {
    BASE: 'inquiries',
    PRODUCT_INQUIRIES: 'products/:productId/inquiries',
    ANSWER: ':id/answer',
    ME: 'me',
  },
  SUPPORT: {
    BASE: 'support',
    TICKETS: 'tickets',
    MY_TICKETS: 'tickets/me',
    ADMIN_TICKETS: 'admin/support/tickets',
    ANSWER: ':id/answer',
  },
  FAQ: {
    BASE: 'faq',
    SEARCH: 'search',
    ADMIN_FAQ: 'admin/faq',
    NOTICES: 'notices',
    ADMIN_NOTICES: 'admin/notices',
  },
  ACTIVITY: {
    BASE: 'activities',
    RECENT_PRODUCTS: 'recent-products',
    SEARCHES: 'searches',
  },
  CHAT: {
    BASE: 'chat',
    ROOMS: 'rooms',
    JOIN_ROOM: 'rooms/:id/join',
    MESSAGES: 'rooms/:id/messages',
  },
  PUSH: {
    BASE: 'push',
    SUBSCRIPTIONS: 'subscriptions',
    UNSUBSCRIBE: 'subscriptions/unsubscribe',
    PREFERENCES: 'preferences',
  },
  PREDICTION: {
    BASE: 'predictions',
    PRODUCT_PRICE_TREND: 'products/:productId/price-trend',
  },
  DEAL: {
    BASE: 'deals',
    ADMIN: 'admin',
    ADMIN_DETAIL: 'admin/:id',
  },
  RECOMMENDATION: {
    BASE: 'recommendations',
    PERSONAL: 'personal',
    TRENDING: 'trending',
  },
  RANKING: {
    BASE: 'rankings',
    POPULAR_PRODUCTS: 'products/popular',
    POPULAR_KEYWORDS: 'keywords/popular',
    ADMIN_RECALCULATE: 'admin/recalculate',
  },
  FRAUD: {
    BASE: 'fraud',
    ALERTS: 'alerts',
    ALERT_APPROVE: 'alerts/:id/approve',
    ALERT_REJECT: 'alerts/:id/reject',
    REAL_PRICE: 'products/:id/real-price',
    EFFECTIVE_PRICES: 'products/:productId/effective-prices',
    ANOMALIES: 'products/:productId/anomalies',
    ADMIN_SCAN: 'admin/products/:productId/scan',
    ADMIN_FLAGS: 'admin/products/:productId/flags',
  },
  TRUST: {
    BASE: 'trust',
    SELLER: 'sellers/:sellerId',
    HISTORY: 'sellers/:sellerId/history',
    ADMIN_RECALCULATE: 'admin/sellers/:sellerId/recalculate',
  },
  I18N: {
    BASE: 'i18n',
    TRANSLATIONS: 'translations',
    ADMIN_TRANSLATIONS: 'admin/translations',
    ADMIN_TRANSLATION_DETAIL: 'admin/translations/:id',
    EXCHANGE_RATES: 'exchange-rates',
    ADMIN_EXCHANGE_RATES: 'admin/exchange-rates',
    CONVERT: 'convert',
  },
  IMAGE: {
    BASE: 'images',
    UPLOAD: 'upload',
    VARIANTS: ':id/variants',
    DETAIL: ':id',
  },
  BADGE: {
    BASE: 'badges',
    ME: 'badges/me',
    USER_BADGES: 'users/:id/badges',
    ADMIN_BASE: 'admin/badges',
    ADMIN_DETAIL: 'admin/badges/:id',
    ADMIN_GRANT: 'admin/badges/:id/grant',
    ADMIN_REVOKE: 'admin/badges/:id/revoke/:userId',
  },
  PC_BUILDER: {
    BASE: 'pc-builds',
    DETAIL: ':id',
    PARTS: ':id/parts',
    PART_DETAIL: ':id/parts/:partId',
    COMPATIBILITY: ':id/compatibility',
    SHARE: ':id/share',
    SHARED: 'shared/:shareCode',
    POPULAR: 'popular',
    ADMIN_COMPATIBILITY_RULES: 'admin/compatibility-rules',
    ADMIN_COMPATIBILITY_RULE_DETAIL: 'admin/compatibility-rules/:id',
  },
  FRIEND: {
    BASE: 'friends',
    REQUEST: 'request/:userId',
    ACCEPT: 'request/:friendshipId/accept',
    REJECT: 'request/:friendshipId/reject',
    REQUESTS_RECEIVED: 'requests/received',
    REQUESTS_SENT: 'requests/sent',
    FEED: 'feed',
    BLOCK: 'block/:userId',
    DETAIL: ':userId',
  },
  NEWS: {
    BASE: 'news',
    CATEGORIES: 'categories',
    DETAIL: ':id',
  },
  MATCHING: {
    BASE: 'matching',
    PENDING: 'pending',
    APPROVE: ':id/approve',
    REJECT: ':id/reject',
    AUTO_MATCH: 'auto-match',
    STATS: 'stats',
  },
  ANALYTICS: {
    BASE: 'analytics',
    LOWEST_EVER: 'products/:id/lowest-ever',
    UNIT_PRICE: 'products/:id/unit-price',
  },
  USED_MARKET: {
    BASE: 'used-market',
    PRODUCT_PRICE: 'products/:id/price',
    CATEGORY_PRICES: 'categories/:id/prices',
    PC_BUILD_ESTIMATE: 'pc-builds/:buildId/estimate',
  },
  MEDIA: {
    BASE: 'media',
    UPLOAD: 'upload',
    PRESIGNED_URL: 'presigned-url',
    STREAM: 'stream/:id',
    DETAIL: ':id',
    METADATA: ':id/metadata',
  },
  SHORTFORM: {
    BASE: 'shortforms',
    DETAIL: ':id',
    LIKE: ':id/like',
    COMMENTS: ':id/comments',
    RANKING: 'ranking/list',
    USER: 'user/:userId',
  },
  HEALTH: {
    BASE: 'health',
  },
} as const;

