# Generated by Django 5.2.12 on 2026-04-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
        ("cart", "0001_initial"),
        ("commerce", "0001_initial"),
        ("order", "0001_initial"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="Payment"),
                migrations.DeleteModel(name="OrderItem"),
                migrations.DeleteModel(name="Order"),
                migrations.DeleteModel(name="Address"),
                migrations.DeleteModel(name="CartItem"),
            ],
            database_operations=[],
        ),
    ]

