# Generated by Django 5.2.12 on 2026-04-02 06:08

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_specdefinition_productspec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('trust_score', models.IntegerField(default=0)),
                ('trust_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sellers',
                'indexes': [models.Index(fields=['is_active'], name='idx_sellers_active')],
            },
        ),
        migrations.CreateModel(
            name='PriceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('shipping_cost', models.IntegerField(default=0)),
                ('shipping_info', models.CharField(blank=True, max_length=100, null=True)),
                ('product_url', models.CharField(max_length=1000)),
                ('shipping_fee', models.IntegerField(default=0)),
                ('shipping_type', models.CharField(choices=[('FREE', 'Free'), ('PAID', 'Paid'), ('CONDITIONAL', 'Conditional')], default='PAID', max_length=12)),
                ('total_price', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('price'), '+', models.F('shipping_fee')), output_field=models.IntegerField())),
                ('click_count', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('crawled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_entries', to='catalog.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_entries', to='pricing.seller')),
            ],
            options={
                'db_table': 'price_entries',
                'indexes': [models.Index(fields=['product', 'price'], name='idx_price_entry_prod_price')],
                'constraints': [models.UniqueConstraint(fields=('product', 'seller'), name='uq_price_entries')],
            },
        ),
    ]
