# Generated by Django 5.2.12 on 2026-04-02 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_specdefinition_productspec_and_more'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.IntegerField()),
                ('is_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'price_alerts',
                'indexes': [models.Index(fields=['is_active', 'is_triggered'], name='idx_price_alert_state')],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='uq_price_alerts')],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lowest_price', models.IntegerField()),
                ('average_price', models.IntegerField()),
                ('highest_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history_entries', to='catalog.product')),
            ],
            options={
                'db_table': 'price_history',
                'indexes': [models.Index(fields=['-date'], name='idx_price_hist_date')],
                'constraints': [models.UniqueConstraint(fields=('product', 'date'), name='uq_price_history')],
            },
        ),
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('predicted_price', models.IntegerField()),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=3)),
                ('trend', models.CharField(choices=[('RISING', 'Rising'), ('FALLING', 'Falling'), ('STABLE', 'Stable')], max_length=10)),
                ('trend_strength', models.DecimalField(decimal_places=2, max_digits=3)),
                ('moving_avg_7d', models.IntegerField(blank=True, null=True)),
                ('moving_avg_30d', models.IntegerField(blank=True, null=True)),
                ('recommendation', models.CharField(choices=[('BUY_NOW', 'Buy now'), ('BUY_SOON', 'Buy soon'), ('WAIT', 'Wait'), ('HOLD', 'Hold')], max_length=10)),
                ('seasonality_note', models.CharField(blank=True, max_length=200, null=True)),
                ('calculated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_predictions', to='catalog.product')),
            ],
            options={
                'db_table': 'price_predictions',
                'indexes': [models.Index(fields=['prediction_date'], name='idx_price_pred_date')],
                'constraints': [models.UniqueConstraint(fields=('product', 'prediction_date'), name='uq_price_predictions')],
            },
        ),
    ]
