# Generated by Django 5.2.12 on 2026-04-02 05:26

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('USER', 'User'), ('SELLER', 'Seller'), ('ADMIN', 'Admin')], default='USER', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=10)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('search_history_enabled', models.BooleanField(default=True)),
                ('point', models.IntegerField(default=0)),
                ('preferred_locale', models.CharField(default='ko', max_length=5)),
                ('preferred_currency', models.CharField(default='KRW', max_length=3)),
                ('refresh_token', models.CharField(blank=True, max_length=500, null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['status'], name='idx_users_status'), models.Index(fields=['role'], name='idx_users_role')],
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
    ]
