# Generated by Django 5.2.12 on 2026-04-04 11:28

import django.db.models.deletion
from django.db.models import Q
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SIGNUP', 'Signup'), ('PASSWORD_RESET', 'Password reset')], max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('attempt_count', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verifications',
                'indexes': [models.Index(fields=['user', 'type'], name='idx_email_verif_user_type'), models.Index(fields=['user', 'code', 'type'], name='idx_email_verif_code'), models.Index(fields=['expires_at'], name='idx_email_verif_expires')],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('naver', 'Naver'), ('kakao', 'Kakao'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('provider_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_accounts',
                'indexes': [models.Index(fields=['user'], name='idx_social_accounts_user'), models.Index(fields=['provider'], name='idx_social_accounts_provider')],
                'constraints': [models.UniqueConstraint(condition=Q(deleted_at__isnull=True), fields=('provider', 'provider_user_id'), name='uq_social_accounts_provider_user')],
            },
        ),
    ]
